### ISSUE TITLE
PostSharp 6.10.10 uses SharpCompress 0.23 Which has the Partial Path Traversal Vulnerability

### ISSUE THREAD

**Issue by PandaBakeOff** [postsharp/PostSharp.Engineering#30]
PostSharp 6.10.10 relies on SharpCompress 0.23:

![image](https://user-images.githubusercontent.com/104918676/166718782-1e92cb58-6716-45d7-a5b0-0762a4cf7929.png)

![image](https://user-images.githubusercontent.com/104918676/166718884-13bd066a-091b-4662-bd50-a8e18c199312.png)

SharpCompress 0.23 has been flagged by WhiteSource as having the Partial Path Traversal Vulnerability:

![image](https://user-images.githubusercontent.com/104918676/166719201-af6c6ce1-5bf4-4ecd-8329-3d5de9d70e99.png)

![image](https://user-images.githubusercontent.com/104918676/166719295-e1e5c3f8-3fd6-4953-af61-89e985104621.png)

It is recommended to upgrade to latest version of SharpCompress.

Thanks!

**Comment by prochan2** [comment]
Hello, thank you for pointing this out. I have filed a bug and we're going to address this issue.

**Comment by PandaBakeOff** [comment]
Thanks @prochan2!

**Comment by gfraiteur** [comment]
I understand that we are not exposed to the vulnerability because we only decompress what we have compressed ourselves. The vulnerability would be real if we uncompressed untrusted archives.

**Comment by PandaBakeOff** [comment]
@gfraiteur, good to know.

Unfortunately, I don't think vulnerability scans will take that into consideration. It would make also make my company happy to not see the vulnerability pop up.

Regardless, I love PostSharp. I removed a lot of code :)

**Comment by prochan2** [comment]
The SharpCompress dependency has been updated in PostSharp 6.5.22 and 6.10.12.

**Comment by PandaBakeOff** [comment]
Once again, thanks @prochan2!

**Comment by prochan2** [comment]
You're welcome, @PandaBakeOff  :)
